import streamlit as st
from streamlit_folium import st_folium
import folium
import geocoder
import re

# Page settings
st.set_page_config(page_title="Stellar Peer Visualizer", layout="wide")
st.title("@@ Stellar Network Map @@")
st.markdown("Upload your `ipa.txt` (generated by docker exec) to visualize peers.")

# 1. Sidebar: File Upload Form
with st.sidebar:
    st.header("Data Source")
    uploaded_file = st.file_uploader("Choose ipa.txt", type="txt")
    
    # Optional: Limitation for API rate limits
    max_nodes = st.slider("Max nodes to plot", 10, 100, 50)

# 2. Processing Data
ips = []
if uploaded_file is not None:
    # Read the uploaded file
    content = uploaded_file.read().decode("utf-8")
    # Extract IP addresses using Regex
    ips = re.findall(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', content)
    st.success(f"Found {len(ips)} IP addresses.")
else:
    st.info("Waiting for file upload...")

# 3. Generating Map
if ips:
    m = folium.Map(location=[20, 0], zoom_start=2)
    
    # Show progress bar
    progress_text = "Fetching geolocations... please wait."
    my_bar = st.progress(0, text=progress_text)
    
    # To prevent API ban, we limit the count
    plot_ips = ips[:max_nodes]
    
    for i, ip in enumerate(plot_ips):
        g = geocoder.ip(ip)
        if g.latlng:
            folium.Marker(
                location=g.latlng,
                popup=f"IP: {ip}<br>{g.city}, {g.country}",
                tooltip=ip,
                icon=folium.Icon(color="blue", icon="server", prefix="fa")
            ).add_to(m)
        
        # Update progress bar
        my_bar.progress((i + 1) / len(plot_ips), text=progress_text)
    
    my_bar.empty() # Clear progress bar

    # Display Map
    st_folium(m, width="100%", height=600)
    
    if len(ips) > max_nodes:
        st.warning(f"Showing first {max_nodes} nodes only due to API limits.")